@@ -8,5 +8,6 @@ before_script:
 # command to run tests
 script: 
   - lettuce tests
+  - coverage run --omit='*lettuce*,*fuzzywuzzy*' tests/features/steps.py
+  - coverage report
   - nosetests --with-doctest --with-coverage -s app
-after_script:
